version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432:5432
  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - VIRTUAL_HOST=fastapi-staff.localhost
    depends_on:
      - db
    volumes:
      - ./:/code/
    ports:
      - "8000:8000"
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  db-data:
